name: "ChatBubbles"
author: TheTealViper
version: "1.18"
api-version: 1.16
description: "ChatBubbles above players' heads"
main: me.TheTealViper.chatbubbles.ChatBubbles
softdepend: [HolographicDisplays, DecentHolograms, Factions, PlaceholderAPI, Citizens]
commands:
  chatbubble:
    description: Main command
    aliases: [cb]
  chatbubblereload:
    description: Main command
    aliases: [cbreload]
  chatbubbletoggle:
    description: Toggle sending chatbubbles
    aliases: [cbtoggle,cbt]